version: "3.2"

services:

  minio:
    image: bitnami/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: ednoAlmeida
      MINIO_ROOT_PASSWORD: sysMapCamp
      MINIO_SERVER_HOST: localhost
      MINIO_SCHEME: http
      MINIO_API_CORS_ALLOW_ORIGIN: '*'
    networks:
      - mynet

  mc:
    image: minio/mc
    container_name: mc
    network_mode: host
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c " /usr/bin/mc config host add --api s3v2 minio http://localhost:9000/  ednoAlmeida sysMapCamp; /usr/bin/mc rm -r --force minio/first-bucket; /usr/bin/mc mb -p minio/first-bucket; /usr/bin/mc policy set public minio/first-bucket; /usr/bin/mc admin trace minio -a --debug; "

  mongodbsocial:
    image: mongo:latest
    container_name: 'mongodbsocial'
    ports:
      - 27017:27017
    networks:
      - mynet

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/data/:/var/log/rabbitmq
    networks:
      - mynet
    healthcheck:
      test: [ "CMD", "nc", "-z", "http://localhost:15672" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    restart: always
    image: edno28/socialmap-backend 
    depends_on:
      - rabbitmq
      - mongodbsocial
      - minio
    environment:
      PORT: 4000
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
      MONGO_URL: mongodb://mongodbsocial:27017/mydb
      ACCESS_TOKEN_SECRET: thisismytoken
      BUCKET_HOST: http://localhost:9000/
      BUCKET_ENDPOINT: http://minio:9000/
      BUCKET_ACCESS_KEY: ednoAlmeida
      BUCKET_SECRET_KEY: sysMapCamp
      BUCKET_NAME: first-bucket
    ports:
      - 4000:4000
    networks:
      - mynet

      
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    image: edno28/socialfront-dev
    networks:
      - mynet

  nginx:
    depends_on:
      - backend
      - client
    restart: always
    image: edno28/socialmap-nginx
    ports:
      - "3050:80"
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
