apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  externalTrafficPolicy: Local
  type: NodePort
  selector:
    app: mongodb
  ports:
  - nodePort: 30163
    port: 27017
    targetPort: 27017
