apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  externalTrafficPolicy: Local
  type: NodePort
  selector:
    app: nginx
  ports:
  - nodePort: 30164
    port: 80
