apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  type: NodePort
  selector:
    name: rabbitmq-service
  ports:
    - nodePort: 30163
      port: 5672
      targetPort: 5672

---

apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-service
spec:
  replicas: 1
  image: rabbitmq:3.8-management-alpine