kind: PersistentVolume
apiVersion: v1
metadata:
  name: minio-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/minio"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minio-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  selector:
    matchLabels:
      app: minio
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: minio
        role: master
        tier: backend
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: minio
          image: <secret Registry >
          env:
          - name: MINIO_ACCESS_KEY
            value: akey
          - name: MINIO_SECRET_KEY
            value: skey
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: data
              mountPath: /data/ob
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minio-pv-claim

---

apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: minio
    role: master
    tier: backend
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30236
  selector:
    app: minio
    role: master
    tier: backend